global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "devicio-processor"
    static_configs:
      - targets: ["host.docker.internal:2112"]
    metrics_path: "/metrics"
    scrape_interval: 5s
    honor_labels: true
